---
Name: roadblock_country_extensions
---
aSmithSummer\Roadblock\Model\RequestLog:
  extensions:
    - aSmithSummer\RoadblockCountry\Extensions\RequestLogCountryExtension
aSmithSummer\Roadblock\Model\RoadblockRule:
  extensions:
    - aSmithSummer\RoadblockCountry\Extensions\RoadblockRuleCountryExtension
aSmithSummer\Roadblock\Model\RoadblockRuleInspector:
  extensions:
    - aSmithSummer\RoadblockCountry\Extensions\RoadblockRuleInspectorCountryExtension
---
Name: roadblock_country_settings
---
aSmithSummer\RoadblockCountry\Model\CountryIPRange:
  default_country_name: 'Outside New Zealand'
