---
Name: roadblock_country_extensions
---
Roadblock\Model\RequestLog:
  extensions:
    - RoadblockCountry\Extensions\RequestLogCountryExtension
Roadblock\Model\RoadblockRule:
  extensions:
    - RoadblockCountry\Extensions\RoadblockRuleCountryExtension
---
Name: roadblock_country_settings
---
RoadblockCountry\Model\CountryIPRange:
  default_country_name: 'Outside New Zealand'